parameters:
    behat.listener.class: SensioLabs\CeremonyTrackerBundle\Listener\BehatListener
services:
   behat.listener:
       class: %behat.listener.class%
       arguments: 
           - @kernel
       tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
          
   controllers.security:
       class: SensioLabs\CeremonyTrackerBundle\Controller\SecurityController
       arguments:
           - @templating
   
   controllers.list_my_projects:
        class: SensioLabs\CeremonyTrackerBundle\Controller\ListMyProjectsController
        arguments:
            - @use_case.get_manager_projects
            - @security.token
            - @form_view.create_project
            - @templating         
   
   use_case.get_manager_projects:
        class: SensioLabs\CeremonyTracker\GetManagerProjects
        arguments:
            - @repository.projects 
   
   
   repository.projects:
        class:           Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:
            - CeremonyTrackerBundle:Project
   
   
   form_view.create_project:
        class:           Symfony\Component\Form\FormView
        factory_service: form.create_project
        factory_method:  createView
   
   security.token:
        class:           Symfony\Component\Security\Core\Authentication\Token\TokenInterface
        factory_service: security.context
        factory_method:  getToken          